import { createContext, useContext, useState, useEffect } from 'react'

const translations = {
    ro: {
        // Nav
        nav_dashboard: 'Dashboard',
        nav_monitoring: 'Monitoring',
        nav_stopControl: 'Stop Control',
        nav_marketing: 'Marketing',
        nav_searches: 'Căutări',
        nav_results: 'Rezultate',
        nav_prices: 'Prețuri concurenți',
        nav_analytics: 'Analize & KPI',
        nav_radar: 'Radar Promoții',
        nav_competitors: 'Concurenți',
        nav_competitor_products: 'Produse Concurenți',
        nav_brands: 'Brands',
        nav_restaurants: 'Restaurants',
        nav_alerts: 'Alerts',
        nav_events: 'Events',
        nav_rules: 'Rules',
        nav_reports: 'Reports',
        nav_discovery: 'Discovery',
        nav_deliveryZone: 'Zone Livrare',
        nav_settings: 'Setări',
        nav_users: 'Utilizatori',
        nav_user_list: 'Listă Utilizatori',
        nav_role_settings: 'Setări Roluri',
        nav_configurations: 'Configurații',
        nav_history: 'Istoric',
        nav_own_products: 'Produse (Aplicații)',
        nav_iiko_products: 'Meniu POS (iiko)',
        nav_overview: 'Opriri',
        nav_prices_compare: 'Comparație Prețuri',

        // Theme
        theme_light: 'Light Mode',
        theme_dark: 'Dark Mode',

        // Auth
        logout: 'Deconectare',
        login: 'Autentificare',
        email: 'Email',
        password: 'Parolă',

        // Common
        search: 'Caută',
        save: 'Salvează',
        cancel: 'Anulează',
        add: 'Adaugă',
        edit: 'Editează',
        delete: 'Șterge',
        loading: 'Se încarcă...',
        all: 'Toate',
        today: 'Azi',
        export_excel: 'Export Excel',
        filters: 'Filtre',
        results: 'rezultate',
        page: 'Pagina',
        per_page: 'Per pag',
        back: 'Înapoi',
        close: 'Închide',
        confirm: 'Confirmi?',
        yes: 'Da',
        no: 'Nu',

        // Marketing
        marketing_title: 'Intelligence Competitiv',
        marketing_subtitle: 'Monitorizare automată concurență · Prețuri · Produse · Evoluție',
        tab_config: 'Configurații',
        tab_results: 'Rezultate',
        tab_history: 'Istoric',
        view_chronological: 'Cronologic',
        view_by_brand: 'Pe brand',
        view_by_city: 'Pe Oraș',
        view_by_product: 'Produs',
        run_all: 'Rulează Toate',
        add_search: 'Adaugă Căutare',
        rank_history: 'Istoric poziții',
        products_prices: 'Produse și prețuri',
        checks: 'Verificări',
        appearances: 'Apariții',
        best_rank: 'Best Rank',
        rating: 'Rating',
        locations: 'Locații',
        products: 'Produse',
        cities: 'Locații',
        platforms: 'Platforme',
        brands_count: 'Branduri',
        back_to_history: 'Înapoi la Istoric',
        back_to_cities: 'Înapoi la Orașe',
        open_on_platform: 'Deschide pe platformă',
        filter_brand: 'Filtrare brand…',
        filter_city: 'Filtrare oraș…',

        // Delivery Zone
        dz_title: 'Zone Livrare',
        dz_subtitle: 'Multiple adrese per restaurant · verificare 1-5 km · istoric zilnic',
        tab_configs: '⚙ Configurații',
        tab_history_dz: '📋 Istoric',
        import_restaurants: '⬇ Import Restaurante',
        run_all_dz: 'Rulează Toate',
        add_restaurant: 'Adaugă Restaurant',
        no_restaurants: 'Niciun restaurant configurat',
        verify: 'Verifică',
        verifying: 'Se verifică...',
        no_history: 'Niciun istoric',
        run_check_hint: 'Rulează o verificare din tab-ul Configurații',
        address: 'Adresă',
        add_address: '+ Adaugă adresă',
        geocode: '📍 Geo',
        config_name: 'NUME CONFIGURAȚIE',
        restaurant_name: 'RESTAURANT (al nostru)',
        brand_searched: 'BRAND CĂUTAT',
        platform: 'PLATFORMĂ',
        city: 'ORAȘ',

        // Settings
        settings_title: 'Setări',
        settings_profile: 'Profil',
        settings_avatar: 'Avatar',
        settings_display_name: 'Nume afișat',
        settings_language: 'Limbă',
        settings_theme: 'Temă',
        settings_save: 'Salvează setările',
        settings_saved: 'Salvat!',
        upload_avatar: 'Încarcă avatar',
        remove_avatar: 'Elimină',

        // Competitors
        competitors_title: 'Concurenți',

        // Dashboard
        dashboard_title: 'Dashboard',
        total_restaurants: 'Restaurante active',
        active_monitoring: 'Monitorizare activă',
        alerts_today: 'Alerte astăzi',
        revenue_at_risk: 'Venituri la risc',
    },
    en: {
        // Nav
        nav_dashboard: 'Dashboard',
        nav_monitoring: 'Monitoring',
        nav_stopControl: 'Stop Control',
        nav_marketing: 'Marketing',
        nav_searches: 'Searches',
        nav_results: 'Results',
        nav_prices: 'Competitor Prices',
        nav_analytics: 'Analytics & KPIs',
        nav_radar: 'Promotions Radar',
        nav_competitors: 'Competitors',
        nav_competitor_products: 'Competitor Products',
        nav_brands: 'Brands',
        nav_restaurants: 'Restaurants',
        nav_alerts: 'Alerts',
        nav_events: 'Events',
        nav_rules: 'Rules',
        nav_reports: 'Reports',
        nav_discovery: 'Discovery',
        nav_deliveryZone: 'Delivery Zones',
        nav_settings: 'Settings',
        nav_users: 'Users',
        nav_user_list: 'Users List',
        nav_role_settings: 'Role Settings',
        nav_configurations: 'Configurations',
        nav_history: 'History',
        nav_own_products: 'Platform Products',
        nav_iiko_products: 'POS Products (iiko)',
        nav_overview: 'Overview',
        nav_prices_compare: 'Prices',

        // Theme
        theme_light: 'Light Mode',
        theme_dark: 'Dark Mode',

        // Auth
        logout: 'Log Out',
        login: 'Sign In',
        email: 'Email',
        password: 'Password',

        // Common
        search: 'Search',
        save: 'Save',
        cancel: 'Cancel',
        add: 'Add',
        edit: 'Edit',
        delete: 'Delete',
        loading: 'Loading...',
        all: 'All',
        today: 'Today',
        export_excel: 'Export Excel',
        filters: 'Filters',
        results: 'results',
        page: 'Page',
        per_page: 'Per page',
        back: 'Back',
        close: 'Close',
        confirm: 'Confirm?',
        yes: 'Yes',
        no: 'No',

        // Marketing
        marketing_title: 'Competitive Intelligence',
        marketing_subtitle: 'Automated competitor monitoring · Prices · Products · Evolution',
        tab_config: 'Configuration',
        tab_results: 'Results',
        tab_history: 'History',
        view_chronological: 'Chronological',
        view_by_brand: 'By Brand',
        view_by_city: 'By City',
        view_by_product: 'Product',
        run_all: 'Run All',
        add_search: 'Add Search',
        rank_history: 'Position History',
        products_prices: 'Products & Prices',
        checks: 'Checks',
        appearances: 'Appearances',
        best_rank: 'Best Rank',
        rating: 'Rating',
        locations: 'Locations',
        products: 'Products',
        cities: 'Locations',
        platforms: 'Platforms',
        brands_count: 'Brands',
        back_to_history: 'Back to History',
        back_to_cities: 'Back to Cities',
        open_on_platform: 'Open on platform',
        filter_brand: 'Filter brand…',
        filter_city: 'Filter city…',

        // Delivery Zone
        dz_title: 'Delivery Zones',
        dz_subtitle: 'Multiple addresses per restaurant · check 1-5 km · daily history',
        tab_configs: '⚙ Configurations',
        tab_history_dz: '📋 History',
        import_restaurants: '⬇ Import Restaurants',
        run_all_dz: 'Run All',
        add_restaurant: 'Add Restaurant',
        no_restaurants: 'No restaurants configured',
        verify: 'Check',
        verifying: 'Checking...',
        no_history: 'No history',
        run_check_hint: 'Run a check from the Configurations tab',
        address: 'Address',
        add_address: '+ Add address',
        geocode: '📍 Geo',
        config_name: 'CONFIG NAME',
        restaurant_name: 'RESTAURANT (ours)',
        brand_searched: 'BRAND SEARCHED',
        platform: 'PLATFORM',
        city: 'CITY',

        // Settings
        settings_title: 'Settings',
        settings_profile: 'Profile',
        settings_avatar: 'Avatar',
        settings_display_name: 'Display Name',
        settings_language: 'Language',
        settings_theme: 'Theme',
        settings_save: 'Save Settings',
        settings_saved: 'Saved!',
        upload_avatar: 'Upload avatar',
        remove_avatar: 'Remove',

        // Competitors
        competitors_title: 'Competitors',

        // Dashboard
        dashboard_title: 'Dashboard',
        total_restaurants: 'Active restaurants',
        active_monitoring: 'Active monitoring',
        alerts_today: 'Alerts today',
        revenue_at_risk: 'Revenue at risk',
    },
    ru: {
        // Nav
        nav_dashboard: 'Аналитика',
        nav_monitoring: 'Мониторинг',
        nav_stopControl: 'Стоп-Контроль',
        nav_marketing: 'Маркетинг',
        nav_searches: 'Поиски',
        nav_results: 'Результаты',
        nav_prices: 'Цены конкурентов',
        nav_analytics: 'Аналитика и KPI',
        nav_radar: 'Радар акций',
        nav_competitors: 'Конкуренты',
        nav_competitor_products: 'Продукты конкурентов',
        nav_brands: 'Бренды',
        nav_restaurants: 'Рестораны',
        nav_alerts: 'Оповещения',
        nav_events: 'События',
        nav_rules: 'Правила',
        nav_reports: 'Отчеты',
        nav_discovery: 'Открытия',
        nav_deliveryZone: 'Зоны Доставки',
        nav_settings: 'Настройки',
        nav_users: 'Пользователи',
        nav_user_list: 'Список пользователей',
        nav_role_settings: 'Настройки ролей',
        nav_configurations: 'Конфигурации',
        nav_history: 'История',
        nav_own_products: 'Свои продукты (агр.)',
        nav_iiko_products: 'Меню POS (iiko)',
        nav_overview: 'Остановки',
        nav_prices_compare: 'Сравнение цен',

        // Theme
        theme_light: 'Светлая тема',
        theme_dark: 'Темная тема',

        // Auth
        logout: 'Выйти',
        login: 'Войти',
        email: 'Эл. почта',
        password: 'Пароль',

        // Common
        search: 'Поиск',
        save: 'Сохранить',
        cancel: 'Отмена',
        add: 'Добавить',
        edit: 'Изменить',
        delete: 'Удалить',
        loading: 'Загрузка...',
        all: 'Все',
        today: 'Сегодня',
        export_excel: 'Экспорт Excel',
        filters: 'Фильтры',
        results: 'результатов',
        page: 'Страница',
        per_page: 'На стр.',
        back: 'Назад',
        close: 'Закрыть',
        confirm: 'Подтвердить?',
        yes: 'Да',
        no: 'Нет',

        // Marketing
        marketing_title: 'Конкурентная разведка',
        marketing_subtitle: 'Автоматизированный мониторинг конкурентов · Цены · Продукты · Динамика',
        tab_config: 'Конфигурация',
        tab_results: 'Результаты',
        tab_history: 'История',
        view_chronological: 'Хронология',
        view_by_brand: 'По бренду',
        view_by_city: 'По городу',
        view_by_product: 'Продукт',
        run_all: 'Запустить всё',
        add_search: 'Добавить поиск',
        rank_history: 'История позиций',
        products_prices: 'Продукты и цены',
        checks: 'Проверки',
        appearances: 'Появления',
        best_rank: 'Лучшая позиция',
        rating: 'Рейтинг',
        locations: 'Локации',
        products: 'Продукты',
        cities: 'Локации',
        platforms: 'Платформы',
        brands_count: 'Бренды',
        back_to_history: 'К истории',
        back_to_cities: 'К городам',
        open_on_platform: 'Открыть на платформе',
        filter_brand: 'Фильтр бренда…',
        filter_city: 'Фильтр города…',

        // Delivery Zone
        dz_title: 'Зоны доставки',
        dz_subtitle: 'Несколько адресов на ресторан · проверка 1-5 км · проверка',
        tab_configs: '⚙ Конфигурации',
        tab_history_dz: '📋 История',
        import_restaurants: '⬇ Импорт ресторанов',
        run_all_dz: 'Запустить всё',
        add_restaurant: 'Добавить',
        no_restaurants: 'Нет ресторанов',
        verify: 'Проверить',
        verifying: 'Проверка...',
        no_history: 'Нет истории',
        run_check_hint: 'Запустите проверку',
        address: 'Адрес',
        add_address: '+ Адрес',
        geocode: '📍 Гео',
        config_name: 'ИМЯ КОНФИГ.',
        restaurant_name: 'РЕСТОРАН',
        brand_searched: 'ИСКОМЫЙ БРЕНД',
        platform: 'ПЛАТФОРМА',
        city: 'ГОРОД',

        // Settings
        settings_title: 'Настройки',
        settings_profile: 'Профиль',
        settings_avatar: 'Аватар',
        settings_display_name: 'Имя',
        settings_language: 'Язык',
        settings_theme: 'Тема',
        settings_save: 'Сохранить',
        settings_saved: 'Сохранено!',
        upload_avatar: 'Загрузить',
        remove_avatar: 'Удалить',

        // Competitors
        competitors_title: 'Конкуренты',

        // Dashboard
        dashboard_title: 'Дешборд',
        total_restaurants: 'Активные рестораны',
        active_monitoring: 'Мониторинг',
        alerts_today: 'Оповещения сегодня',
        revenue_at_risk: 'Доходы под угрозой',
    }
}

const LanguageContext = createContext(null)

export const LanguageProvider = ({ children }) => {
    const [lang, setLang] = useState(() => localStorage.getItem('lang') || 'ro')

    useEffect(() => {
        localStorage.setItem('lang', lang)
    }, [lang])

    const t = (key) => translations[lang]?.[key] || translations['ro']?.[key] || key

    return (
        <LanguageContext.Provider value={{ lang, setLang, t, translations }}>
            {children}
        </LanguageContext.Provider>
    )
}

export const useLanguage = () => useContext(LanguageContext)
